language:
  reminder: "&fFile d'attente: &c{queue} &8┃ &fPosition &c{position}&7/&c{total} &8┃ &fQuitter: &c/leavequeue"
  added:
    - "&fVous avez rejoint la file d'attente du serveur &a{queue}&f."
  removed:
    - "&fVous avez quitté la file d'attente du serveur &c{queue}&f."